module.exports = [
    {
      id: 1,
      name: 'Product 1',
      price: 140,
      discount: 5,
      description: 'Description for Product 1',
      image: 'https://infinite-ravine-05016.herokuapp.com/images/image_1.png',
      created_at: new Date(),
      updated_at: new Date(),
   },
   {
    id: 2,
    name: 'Product 2',
    price: 150,
    discount: 5,
    description: 'Description for Product 2',
    image: 'https://infinite-ravine-05016.herokuapp.com/images/image_2.png',
    created_at: new Date(),
    updated_at: new Date(),
 },
 {
    id: 3,
    name: 'Product 3',
    price: 150,
    discount: 5,
    description: 'Description for Product 3',
    image: 'https://infinite-ravine-05016.herokuapp.com/images/image_3.png',
    created_at: new Date(),
    updated_at: new Date(),
 },
 {
    id: 4,
    name: 'Product 4',
    price: 150,
    discount: 5,
    description: 'Description for Product 4',
    image: 'https://infinite-ravine-05016.herokuapp.com/images/image_1.png',
    created_at: new Date(),
    updated_at: new Date(),
 },
 {
    id: 5,
    name: 'Product 5',
    price: 150,
    discount: 5,
    description: 'Description for Product 5',
    image: 'https://infinite-ravine-05016.herokuapp.com/images/image_1.png',
    created_at: new Date(),
    updated_at: new Date(),
 },
 {
    id: 6,
    name: 'Product 6',
    price: 150,
    discount: 5,
    description: 'Description for Product 6',
    image: 'https://infinite-ravine-05016.herokuapp.com/images/image_1.png',
    created_at: new Date(),
    updated_at: new Date(),
 },
 {
    id: 7,
    name: 'Product 7',
    price: 150,
    discount: 5,
    description: 'Description for Product 7',
    image: 'https://infinite-ravine-05016.herokuapp.com/images/image_1.png',
    created_at: new Date(),
    updated_at: new Date(),
 },
 {
    id: 8,
    name: 'Product 8',
    price: 150,
    discount: 5,
    description: 'Description for Product 8',
    image: 'https://infinite-ravine-05016.herokuapp.com/images/image_1.png',
    created_at: new Date(),
    updated_at: new Date(),
 },
 {
    id: 9,
    name: 'Product 9',
    price: 110,
    discount: 0,
    description: 'Description for Product 9',
    image: 'https://infinite-ravine-05016.herokuapp.com/images/image_3.png',
    created_at: new Date(),
    updated_at: new Date(),
 },
 {
    id: 10,
    name: 'Product 9',
    price: 110,
    discount: 0,
    description: 'Description for Product 9',
    image: 'https://infinite-ravine-05016.herokuapp.com/images/image_2.png',
    created_at: new Date(),
    updated_at: new Date(),
 },
 {
    id: 11,
    name: 'Product 19',
    price: 120,
    discount: 0,
    description: 'Description for Product 9',
    image: 'https://infinite-ravine-05016.herokuapp.com/images/image_1.png',
    created_at: new Date(),
    updated_at: new Date(),
 },
 {
    id: 12,
    name: 'Product 19',
    price: 120,
    discount: 0,
    description: 'Description for Product 9',
    image: 'https://infinite-ravine-05016.herokuapp.com/images/image_2.png',
    created_at: new Date(),
    updated_at: new Date(),
 },
 {
    id: 13,
    name: 'Product 19',
    price: 120,
    discount: 0,
    description: 'Description for Product 9',
    image: 'https://infinite-ravine-05016.herokuapp.com/images/image_2.png',
    created_at: new Date(),
    updated_at: new Date(),
 },
 {
    id: 14,
    name: 'Product 19',
    price: 120,
    discount: 0,
    description: 'Description for Product 9',
    image: 'https://infinite-ravine-05016.herokuapp.com/images/image_1.png',
    created_at: new Date(),
    updated_at: new Date(),
 },
 {
    id: 15,
    name: 'Product 19',
    price: 120,
    discount: 0,
    description: 'Description for Product 9',
    image: 'https://infinite-ravine-05016.herokuapp.com/images/image_3.png',
    created_at: new Date(),
    updated_at: new Date(),
 },
 {
    id: 16,
    name: 'Product 19',
    price: 120,
    discount: 0,
    description: 'Description for Product 9',
    image: 'https://infinite-ravine-05016.herokuapp.com/images/image_2.png',
    created_at: new Date(),
    updated_at: new Date(),
 }
  ]